#!/bin/zsh

REPOSITORY_ROOT_DIR=$(cd $(dirname $0) && pwd)

# zsh
if [ "$SHELL" != "/bin/zsh" ]; then
  echo "change shell (zsh)"
  chsh -s /bin/zsh $USER
fi

# screen setup
mkdir -p ~/.screen

# create symbolic links
echo $0
echo ${REPOSITORY_ROOT_DIR}
for dotfile in $(find ${REPOSITORY_ROOT_DIR} -name ".*" -type f | grep -v '\.git$')
do
  FILENAME=$(basename ${dotfile})
  rm -f ~/${FILENAME}
  ln -s ${dotfile} ~/${FILENAME}
done

if [ -d $DROPBOX_HOME/Backup/.ssh -a ! -L ~/.ssh ]; then
  ln -s $DROPBOX_HOME/Backup/.ssh ~/.ssh
else
  mkdir -p ~/.ssh
fi
rm -rf ~/.ssh/config ~/.ssh/authorized_keys
ln -s {${REPOSITORY_ROOT_DIR},~}/.ssh/config
ln -s {${REPOSITORY_ROOT_DIR},~}/.ssh/authorized_keys

rm -rf ~/.vim
ln -s {${REPOSITORY_ROOT_DIR},~}/.vim

# Generate SSH keys
if [ ! -f ~/.ssh/github ]; then
  echo "==== Generate github SSH key ====" 1>&2
  ssh-keygen -t ed25519 -f ~/.ssh/github -C "github key for $(whoami)@$(hostname) on $(date +%Y-%m-%d)"
fi
if [ ! -f ~/.ssh/bitbucket ]; then
  echo "==== Generate bitbucket SSH key ====" 1>&2
  ssh-keygen -t rsa -b $((1024 * 8)) -f ~/.ssh/bitbucket -C "bitbucket key for $(whoami)@$(hostname) on $(date +%Y-%m-%d)"
fi

# cron
rm -rf ~/.crontab
ln -s {${REPOSITORY_ROOT_DIR},~}/.crontab
crontab ${REPOSITORY_ROOT_DIR}/crontab

# OS specific setup
if [ -f /etc/ec2_version ]; then
  OS=$(cat /etc/ec2_version | awk '{ print $1 }')
  case $OS in
    Ubuntu) ./ubuntu-setup ;;
  esac
fi
